# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jargon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jargontext',
            name='chunks',
        ),
        migrations.AddField(
            model_name='chunk',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chunk',
            name='tag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jargontext',
            name='tagged_text',
            field=models.ManyToManyField(related_name='_jargontext_tagged_text_+', to='jargon.Chunk'),
        ),
    ]
